import { recordedAction } from './support/recorded-actions.js';
import { test, expect } from '@playwright/test';
import { readFileSync } from 'node:fs';

test('overview shows failure output without opening passed tests', async ({ page }) => {
 const asset = JSON.parse(readFileSync('public/build/manifest.json','utf8'))['resources/js/app.tsx'];
 const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1">${(asset.css??[]).map(file=>`<link rel="stylesheet" href="/build/${file}">`).join('')}<script type="module" src="/build/${asset.file}"></script></head><body><div id="root"></div><script id="hub-data" type="application/json"></script></body></html>`;
 const testCase = (key, outcome, attempts) => ({key,title:key,project:'desktop',outcome,expectedStatus:'passed',duration:10,attachments:[],attempts});
 const attempt = (status, errors=[], retry=0) => ({status,errors,retry,duration:10});
 const run = {id:2,phase:'after',status:'complete',capture_video:true,report:{outcome:'failed',errors:['Runner diagnostic'],tests:[
  testCase('Successful checkout','expected',[attempt('passed')]),
  testCase('Broken checkout','unexpected',[attempt('failed',['Expected confirmation, received error'])]),
  testCase('Retry checkout','flaky',[attempt('timedOut',['Checkout timed out']),attempt('passed',[],1)])
 ]}};
 run.report.tests[1].diagnostics = {console:['error: Payment unavailable'],network:['POST /api/payments 503'],warnings:['Response body unavailable']};
 const baseline = {...run,id:1,phase:'before',report:{outcome:'passed',tests:[testCase('Successful checkout','expected',[attempt('passed')])]}};
 const secondBaseline = {...baseline,id:3}; const secondRun = {...run,id:4};
 const payload = {page:'session',csrf:'test',old:{},errors:[],props:{active:false,session:{id:1,title:'Overview fixture',environment:{name:'Local',project:{name:'Fixture'}},suites:[{id:1,name:'Checkout',config:'playwright.config.ts',test_catalog:[{key:'nested',file:'checkout.spec.ts',title:'checkout.spec.ts › Checkout › Saved card › completes',project:'desktop'}],selected_tests:null,runs:[baseline,run]},{id:2,name:'Refunds',config:'refunds.config.ts',test_catalog:[],selected_tests:null,runs:[secondBaseline,secondRun]}]}}};
 await page.route('**/overview-fixture*', route => route.fulfill({contentType:'text/html',body:html.replace(/(<script id="hub-data"[^>]*>)[\s\S]*?(<\/script>)/,(_,start,end)=>start+JSON.stringify(payload)+end)}));
 await page.goto('/overview-fixture');
 await expect(page.locator('header').getByRole('tab')).toHaveCount(3);
 await expect(page.getByRole('link', {name:'← Back to home',exact:true})).toHaveAttribute('href','/');
 await expect(page.getByRole('tab', {name:'Overview',exact:true})).toHaveAttribute('aria-selected','true');
 const captureTarget = page.getByRole('combobox',{name:'Capture target',exact:true});
 await expect(captureTarget.locator('option')).toHaveText(['All suites','Checkout','Refunds']);
 await recordedAction(page, captureTarget, 'selectOption', '1');
 await expect(page.getByRole('button',{name:'Baseline reused',exact:true}).locator('xpath=ancestor::form')).toHaveAttribute('action','/suites/1/runs');
 await recordedAction(page, captureTarget, 'selectOption', 'all');
 await expect(page.getByRole('button',{name:'Baseline locked',exact:true}).locator('xpath=ancestor::form')).toHaveAttribute('action','/sessions/1/captures');
 const manager = page.getByRole('region',{name:'Playwright suites',exact:true});
 await expect(manager.getByRole('button',{name:'▸ Checkout',exact:true})).toHaveAttribute('aria-expanded','false');
 await recordedAction(page, manager.getByRole('button',{name:'▸ Checkout',exact:true}), 'click');
 await expect(manager.getByRole('button',{name:'▸ checkout.spec.ts',exact:true})).toHaveAttribute('aria-expanded','false');
 await recordedAction(page, manager.getByRole('button',{name:'▸ checkout.spec.ts',exact:true}), 'click');
 await expect(manager.getByRole('button',{name:'▸ Checkout',exact:true})).toHaveAttribute('aria-expanded','false');
 await recordedAction(page, manager.getByRole('button',{name:'▸ Checkout',exact:true}), 'click');
 await recordedAction(page, manager.getByRole('button',{name:'▸ Saved card',exact:true}), 'click');
 await expect(manager.getByRole('checkbox',{name:'Video for checkout.spec.ts › Checkout › Saved card › completes (desktop)',exact:true})).toBeChecked();
 await recordedAction(page, manager.getByRole('checkbox',{name:'Videos for suite Saved card',exact:true}), 'uncheck');
 await expect(manager.getByRole('checkbox',{name:'Videos for file checkout.spec.ts',exact:true})).not.toBeChecked();
 await recordedAction(page, manager.getByRole('button',{name:'▾ Checkout',exact:true}).first(), 'click');

 const suiteSelect = page.getByRole('combobox',{name:'Test suite',exact:true});
 await expect(suiteSelect).toBeVisible();
 await expect(suiteSelect.locator('option')).toHaveText(['All suites','Checkout','Refunds']);
 await recordedAction(page, suiteSelect, 'selectOption', 'all');
 const evidence = page.getByRole('region',{name:'Test coverage summary',exact:true});
 await expect(evidence).toHaveCount(1);
 await expect(evidence.getByRole('region',{name:'Change review',exact:true})).toHaveCount(1);
 await expect(page.getByRole('heading',{name:'What changed. What needs a closer look.',exact:true})).toHaveCount(0);
 await expect(page.getByText('All suites · latest runs · complete',{exact:true})).toBeVisible();
 await expect(page.getByText('Test inventory changes',{exact:true})).toHaveCount(0);
 await expect(page.getByText(/^Changed areas:/)).toHaveCount(0);
 await recordedAction(page, suiteSelect, 'selectOption', '1');
 await expect(page.getByRole('button',{name:'Capture after',exact:true})).toBeVisible();
 const output = page.getByRole('region',{name:'Failure output',exact:true}).first();
 await expect(output.locator('details[open]')).toHaveCount(0);
 for (const summary of await output.locator('summary').all()) await recordedAction(page, summary, 'click');
 await expect(output.getByText('Expected confirmation, received error',{exact:true}).first()).toBeVisible();
 await expect(output.getByText('Checkout timed out',{exact:true}).first()).toBeVisible();
 await expect(output.getByText('Runner diagnostic',{exact:true}).first()).toBeVisible();
 await expect(output.getByText('Checkout · desktop',{exact:true}).first()).toBeVisible();
 await recordedAction(page, evidence.getByRole('button',{name:'Failed 1',exact:true}), 'click');
 const failedTests = evidence.getByRole('region',{name:'Failed tests',exact:true});
 await expect(failedTests).toContainText('Broken checkout');
 await expect(failedTests).not.toContainText('Retry checkout');
 await expect(evidence.getByRole('button',{name:'Failed 1',exact:true})).toHaveAttribute('aria-pressed','true');
 await expect(output.getByText('Successful checkout',{exact:true})).toHaveCount(0);
 await recordedAction(page, page.getByRole('tab',{name:'Videos',exact:true}), 'click');
 await expect(page.getByRole('region',{name:'Test coverage summary',exact:true})).not.toBeVisible();
 await expect(page.getByRole('combobox',{name:'Test suite',exact:true})).not.toBeVisible();
 await recordedAction(page, page.getByRole('tab',{name:'Videos',exact:true}), 'press', 'ArrowRight');
 await expect(page.getByRole('tab',{name:'Dev details',exact:true})).toHaveAttribute('aria-selected','true');
 await recordedAction(page, page.getByRole('tab',{name:'Dev details',exact:true}), 'click');
 const explorer = page.getByRole('region',{name:'Test explorer',exact:true});
 const selected = explorer.getByLabel('Selected test output');
 await expect(selected).toContainText('Expected confirmation, received error');
 await recordedAction(page, explorer.getByRole('button',{name:'Console',exact:true}), 'click');
 await expect(selected).toContainText('error: Payment unavailable');
 await recordedAction(page, explorer.getByRole('button',{name:'Network',exact:true}), 'click');
 await expect(selected).toContainText('POST /api/payments 503');
 await expect(selected).toContainText('Response body unavailable');
 await recordedAction(page, explorer.getByRole('button').filter({hasText:'Successful checkout'}), 'click');
 await expect(selected).toContainText('diagnostics were not recorded');
 await recordedAction(page, explorer.getByRole('button',{name:'Output',exact:true}), 'click');
 await expect(selected).toContainText('PASS');
 await expect(selected).not.toContainText('Expected confirmation');
 await recordedAction(page, explorer.getByRole('button').filter({hasText:'Retry checkout'}), 'click');
 await expect(selected).toContainText('Attempt 1 · timedOut');
 await expect(selected).toContainText('Attempt 2 · passed');
 await recordedAction(page, explorer.getByRole('button',{name:'Run history · 2',exact:true}), 'click');
 await recordedAction(page, explorer.getByRole('button').filter({hasText:'#1 · before'}), 'click');
 await expect(selected).toContainText('PASS');
 await expect(explorer.locator('.explorer-context')).toContainText('before #1');
 await recordedAction(page, explorer.getByLabel('Find a test'), 'fill', 'not-a-test');
 await expect(explorer.getByLabel('Selected test output')).toContainText('No tests match this search.');
 await recordedAction(page, explorer.getByLabel('Find a test'), 'fill', '');
 await page.screenshot({path:'test-results/test-explorer-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/test-explorer-mobile.png',fullPage:true});
 await recordedAction(page, page.getByRole('tab',{name:'Overview',exact:true}), 'click');
 await expect(output.getByText('Expected confirmation, received error',{exact:true}).first()).toBeVisible();
 await page.setViewportSize({width:390,height:844});
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
 await page.screenshot({path:'test-results/failure-overview-mobile.png',fullPage:true});
 await recordedAction(page, page.getByRole('link', {name:'← Back to home',exact:true}), 'click');
 await expect(page.getByRole('heading',{name:'Home',exact:true})).toBeVisible();
});
