import { recordedAction } from './support/recorded-actions.js';
import { test, expect } from '@playwright/test';
import { mkdtempSync, writeFileSync, symlinkSync, rmSync, mkdirSync } from 'node:fs';
import { join, resolve } from 'node:path';
import { execFileSync } from 'node:child_process';

test('video cleanup: a later suite reuses the original baseline even after its suite is removed', async ({ page }, info) => {
 info.annotations.push({ type: 'covers', description: 'change-hub/app/Actions/SessionBaselineAction.php' }, { type: 'covers', description: 'change-hub/app/Actions/ManageTestSuiteAction.php' }, { type: 'covers', description: 'change-hub/app/Actions/QueueSuiteRunAction.php' });
 const repo = mkdtempSync(resolve('storage/framework/testing/shared-baseline-'));
 const git = args => execFileSync('git', args, { cwd: repo });
 try {
  git(['init', '-q']); symlinkSync(resolve('node_modules'), join(repo, 'node_modules'), 'dir'); writeFileSync(join(repo, '.gitignore'), 'node_modules\n'); mkdirSync(join(repo, 'src')); writeFileSync(join(repo, 'src/Home.tsx'), 'export function Home(){return <h1>Home</h1>}');
  writeFileSync(join(repo, 'playwright.config.mjs'), `export default {testDir:'.',testMatch:'*.spec.mjs',timeout:10000,projects:[{name:'desktop'}]}`);
  writeFileSync(join(repo, 'home.spec.mjs'), `import {test,expect} from '@playwright/test';test('existing component',async({page},info)=>{info.annotations.push({type:'covers',description:'src/Home.tsx'});await page.setContent('<h1>Home</h1>');await expect(page.locator('h1')).toHaveText('Home');await page.waitForTimeout(500)})`);
  git(['add', '.']); git(['-c', 'user.name=Test', '-c', 'user.email=test@example.invalid', 'commit', '-qm', 'baseline fixture']);
  await page.goto('/projects/create'); await recordedAction(page, page.getByLabel('Project name', { exact: true }), 'fill', 'Shared baseline fixture'); await recordedAction(page, page.getByLabel('Repository directory', { exact: true }), 'fill', repo); await recordedAction(page, page.getByLabel('Playwright config path', { exact: true }), 'fill', 'playwright.config.mjs'); await recordedAction(page, page.getByLabel('Default suite name', { exact: true }), 'fill', 'Original baseline'); await recordedAction(page, page.getByRole('button', { name: 'Connect project', exact: true }), 'click');
  await recordedAction(page, page.getByRole('button', { name: 'Save environment', exact: true }), 'click'); await recordedAction(page, page.getByLabel('Session title', { exact: true }), 'fill', 'One baseline for every suite'); await recordedAction(page, page.getByRole('button', { name: 'Create session', exact: true }), 'click');
  await recordedAction(page, page.getByRole('button', { name: 'Capture before', exact: true }), 'click'); await expect(page.getByRole('button', { name: 'Baseline locked', exact: true })).toBeVisible({ timeout: 45000 }); await expect(page.locator('[data-refresh]')).toHaveCount(0);
  await recordedAction(page, page.getByRole('button', { name: 'Add tests', exact: true }), 'click'); const dialog = page.getByRole('dialog'); await expect(dialog.getByRole('checkbox')).toHaveCount(1); await recordedAction(page, dialog.getByRole('checkbox'), 'check'); await recordedAction(page, dialog.getByRole('textbox', { name: 'Suite name', exact: true }), 'fill', 'Later comparison'); await recordedAction(page, dialog.getByRole('button', { name: 'Add 1 selected test', exact: true }), 'click'); await expect(dialog).toHaveCount(0);
  const suite = page.getByRole('region', { name: 'Suite Later comparison', exact: true }); await expect(suite.getByRole('button', { name: 'Session baseline reused', exact: true })).toBeDisabled(); await recordedAction(page, suite.getByRole('button', { name: 'Run suite after', exact: true }), 'click'); await expect(page.locator('[data-refresh]')).toBeVisible(); await expect(page.locator('[data-refresh]')).toHaveCount(0, { timeout: 45000 });
  await recordedAction(page, page.getByRole('tab', { name: 'Videos', exact: true }), 'click'); const before = page.getByLabel('Before interaction video', { exact: true }); await expect(before).toBeVisible(); const beforeUrl = await before.getAttribute('src'); expect(beforeUrl).toContain('/baseline-artifacts/');
  await recordedAction(page, page.getByRole('tab', { name: 'Overview', exact: true }), 'click'); const manager = page.getByRole('region', { name: 'Playwright suites', exact: true }); await recordedAction(page, manager.getByRole('button', { name: '▸ Original baseline', exact: true }), 'click'); await recordedAction(page, manager.getByRole('button', { name: 'Remove suite', exact: true }), 'click'); await recordedAction(page, manager.getByRole('button', { name: 'Confirm removal', exact: true }), 'click'); await expect(manager.getByRole('button', { name: '▸ Original baseline', exact: true })).toHaveCount(0); await expect(manager.getByRole('button', { name: '▾ Original baseline', exact: true })).toHaveCount(0);
  await recordedAction(page, page.getByRole('tab', { name: 'Videos', exact: true }), 'click'); await page.reload(); await expect(before).toHaveAttribute('src', beforeUrl); expect((await page.request.get(beforeUrl)).status()).toBe(200); await expect(page.getByLabel('After interaction video', { exact: true })).toBeVisible();
  const html = await (await page.request.get(page.url())).text(); const data = JSON.parse(html.match(/<script id="hub-data" type="application\/json">(.*?)<\/script>/s)[1]); expect(data.props.session.suites).toHaveLength(1); expect(data.props.session.suites[0].runs.every(run => run.phase === 'after')).toBe(true); expect(data.props.session.baseline.runs).toHaveLength(1);
  await info.attach('shared-baseline-preserved', { body: await page.screenshot(), contentType: 'image/png' });
 } finally { rmSync(repo, { recursive: true, force: true }); }
});
