import {test,expect} from '@playwright/test'
import {mkdtempSync,writeFileSync,symlinkSync,rmSync,mkdirSync,readdirSync} from 'node:fs'
import {join,resolve} from 'node:path'
import {execFileSync} from 'node:child_process'

test('video-first captures, developer diffs and suites added during a change',async({page})=>{
 test.setTimeout(150000)
 const repo=mkdtempSync(resolve('storage/framework/testing/suite-'))
 const git=args=>execFileSync('git',args,{cwd:repo})
 const errors=[];page.on('pageerror',error=>errors.push(error.message))
 try {
  git(['init','-q']);symlinkSync(resolve('node_modules'),join(repo,'node_modules'),'dir');writeFileSync(join(repo,'.gitignore'),'node_modules\n')
  mkdirSync(join(repo,'src'))
  writeFileSync(join(repo,'src/App.tsx'),'export function Home() { return <a href="/old">Home</a> }')
  writeFileSync(join(repo,'state.txt'),'Before feature')
  writeFileSync(join(repo,'playwright.config.mjs'),`export default {testDir:'.',testMatch:'*.spec.mjs',timeout:10000,use:{video:'on'},projects:[{name:'desktop'},{name:'mobile',use:{viewport:{width:390,height:844}}}]}`)
  writeFileSync(join(repo,'resume.spec.mjs'),`import {test,expect} from '@playwright/test';test('opens resume',async({page})=>{await page.setContent('<h1>Resume</h1>');await expect(page.locator('h1')).toHaveText('Resume')})`)
  writeFileSync(join(repo,'feature.spec.mjs'),`import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';test('opens component',async({page},info)=>{info.annotations.push({type:'covers',description:'src/App.tsx'});const title=readFileSync(new URL('./state.txt',import.meta.url),'utf8');await page.route('http://fixture.test/**',route=>route.fulfill({contentType:'text/html',body:'<main><h1>'+title+'</h1><button>Save</button></main>'}));await page.goto('http://fixture.test/');await page.evaluate(value=>console.log(value),title);await page.getByRole('button').click();await expect(page.locator('h1')).toHaveText(title);await info.attach('checkpoint',{body:await page.screenshot(),contentType:'image/png'});await page.waitForTimeout(700)});`)
  git(['add','.']);git(['-c','user.name=Test','-c','user.email=test@example.invalid','commit','-qm','fixture'])
  await page.goto('/projects/create')
  await page.getByLabel('Project name',{exact:true}).fill('Suite fixture')
  await page.getByLabel('Repository directory',{exact:true}).fill(repo)
  await page.getByLabel('Playwright config path',{exact:true}).fill('playwright.config.mjs')
  await page.getByLabel('Default suite name',{exact:true}).fill('Feature suite')
  await page.getByRole('button',{name:'Connect project',exact:true}).click()
  await page.getByRole('button',{name:'Save environment',exact:true}).click()
  await page.getByLabel('Session title',{exact:true}).fill('Feature comparison')
  await page.getByRole('button',{name:'Create session',exact:true}).click()
  const suite=page.getByRole('region',{name:'Suite Feature suite',exact:true})
  await expect(suite).toBeVisible()
  await expect(page.getByRole('tab',{name:'Videos',exact:true})).toBeVisible()
  await expect(page.getByText('What changed in this view',{exact:true})).toHaveCount(0)
  await suite.getByRole('button',{name:'Refresh test list',exact:true}).click()
  const resumeFile=page.getByRole('checkbox',{name:'Videos for file resume.spec.mjs',exact:true})
  await expect(resumeFile).toBeChecked()
  await resumeFile.uncheck()
  await page.getByRole('button',{name:'Apply video selection',exact:true}).click()
  await expect(resumeFile).not.toBeChecked()
  await page.getByRole('button',{name:'Capture before',exact:true}).click()
  await expect(suite.getByRole('button',{name:'Suite baseline locked',exact:true})).toBeVisible({timeout:45000})
  await expect(suite.locator('.video-pair')).toHaveCount(2)
  const evidence=page.getByRole('region',{name:'Test coverage summary',exact:true})
  await expect(evidence.locator('.test-metrics > div').filter({hasText:'Executed'}).locator('dd')).toHaveText('4')
  await expect(evidence.getByText('New tests: Not compared',{exact:true})).toBeVisible()
  const pair=suite.locator('.video-pair').first()
  const beforeVideo=pair.getByLabel('Before interaction video',{exact:true})
  const beforeURL=await beforeVideo.getAttribute('src')
  await pair.getByRole('button',{name:'Play before from start',exact:true}).click()
  await expect.poll(()=>beforeVideo.evaluate(video=>video.currentTime)).toBeGreaterThan(0)
  writeFileSync(join(repo,'state.txt'),'After feature')
  writeFileSync(join(repo,'src/App.tsx'),'export function Home() { return <a href="/new">Home</a> }; fetch("/api/user")')
  writeFileSync(join(repo,'src/New.ts'),'export type NewSettings = { enabled: boolean }')
  writeFileSync(join(repo,'new.spec.mjs'),`import {test} from '@playwright/test';test.skip('new unfinished behavior',async()=>{});`)
  await page.getByRole('button',{name:'Capture after',exact:true}).click()
  await expect(page.getByRole('button',{name:'Capture after',exact:true})).toBeEnabled({timeout:45000})
  await expect(beforeVideo).toHaveAttribute('src',beforeURL)
  await expect(evidence.locator('.test-metrics > div').filter({hasText:'Executed'}).locator('dd')).toHaveText('4')
  await expect(evidence.locator('.test-metrics > div').filter({hasText:'Skipped'}).locator('dd')).toHaveText('2')
  await expect(evidence.getByText('New tests: 2',{exact:true})).toBeVisible()
  await expect(evidence.getByText('Selected video pairs: 2',{exact:true})).toBeVisible()
  await evidence.getByText('Changed areas: 1 without identified coverage / 2 changed files',{exact:true}).click()
  await expect(evidence.locator('.coverage-area').filter({hasText:'src/New.ts'})).toContainText('Coverage not identified')
  await expect(evidence.locator('.coverage-area').filter({hasText:'src/App.tsx'})).toContainText('2 declared test links')
  await pair.getByRole('button',{name:'Play both from start',exact:true}).click()
  await expect.poll(()=>pair.getByLabel('After interaction video',{exact:true}).evaluate(video=>video.currentTime)).toBeGreaterThan(0)
  await pair.getByRole('button',{name:'Pause both',exact:true}).click()
  await page.getByRole('tab',{name:'Screenshots',exact:true}).click()
  const screenshots=page.getByRole('region',{name:'Screenshot comparisons',exact:true})
  await expect(screenshots.getByRole('status').first()).toContainText('pixels changed')
  await expect(screenshots.getByRole('status').first()).not.toContainText('0 /')
  await expect(screenshots.locator('canvas').first()).toBeVisible()
  await expect(screenshots.locator('canvas')).toHaveCount(2)
  await screenshots.getByRole('combobox',{name:'Capture variant',exact:true}).selectOption({index:1})
  await expect(screenshots.getByRole('status')).toContainText('pixels changed')
  await screenshots.getByRole('button',{name:'Show originals',exact:true}).first().click()
  await expect(screenshots.getByRole('button',{name:'Highlight differences',exact:true}).first()).toHaveAttribute('aria-pressed','false')
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.setViewportSize({width:1440,height:1000})
  await page.getByRole('tab',{name:'Dev details',exact:true}).click()
  const review=page.getByRole('region',{name:'Change review',exact:true})
  await expect(review).toBeVisible()
  await expect(review.locator('.review-area')).toHaveCount(2)
  await review.getByRole('button',{name:'Evidence gaps only',exact:true}).click()
  await expect(review.locator('.review-area')).toHaveCount(1)
  await expect(review.locator('.review-area')).toContainText('src/New.ts')
  await review.getByRole('button',{name:'Evidence gaps only',exact:true}).click()
  await review.getByLabel('Find a changed area').fill('App.tsx')
  await review.locator('.review-area > summary').click()
  await expect(review.locator('.test-result-row')).toHaveCount(2)
  await expect(review.locator('.test-result-row details')).toHaveCount(0)
  await expect(review.getByRole('link',{name:'Video',exact:true}).first()).toBeVisible()
  await expect(review.locator('canvas')).toHaveCount(0)
  await page.screenshot({path:'test-results/change-review-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/change-review-mobile.png',fullPage:true})
  await page.setViewportSize({width:1440,height:1000})
  await page.getByRole('button',{name:'Runtime logs',exact:true}).click()
  const consoleRegion=page.getByRole('region',{name:'Console',exact:true})
  await consoleRegion.locator('summary').first().click()
  await expect(consoleRegion.getByText('log: Before feature',{exact:true}).first()).toBeVisible()
  await expect(consoleRegion.getByText('log: After feature',{exact:true}).first()).toBeVisible()
  const network=page.getByRole('region',{name:'Network',exact:true})
  await expect(network.locator('summary').first()).toContainText('0 differences')
  await page.getByRole('button',{name:'Contract diffs',exact:true}).click()
  const ui=page.getByRole('region',{name:'UI components and navigation',exact:true})
  await ui.locator('.file-diff > summary').click()
  await ui.locator('summary').filter({hasText:'Navigation a'}).click()
  await expect(ui.locator('.diff-line.removed:visible').filter({hasText:'/old'})).toBeVisible()
  await expect(ui.locator('.diff-line.added:visible').filter({hasText:'/new'})).toBeVisible()
  await page.screenshot({path:'test-results/dev-details-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/dev-details-mobile.png',fullPage:true})
  await page.setViewportSize({width:1440,height:1000})
  await page.getByText('Add a Playwright suite',{exact:true}).click()
  await page.getByLabel('Suite name',{exact:true}).fill('New component')
  await page.getByLabel('Test title filter (optional regex)',{exact:true}).fill('opens component')
  await page.getByRole('button',{name:'Add suite',exact:true}).click()
  await page.getByRole('combobox',{name:'Test suite',exact:true}).selectOption({label:'New component'})
  const added=page.getByRole('region',{name:'Suite New component',exact:true})
  await added.getByRole('button',{name:'Refresh test list',exact:true}).click()
  await page.getByRole('checkbox',{name:'Videos for file feature.spec.mjs',exact:true}).uncheck()
  await page.getByRole('button',{name:'Apply video selection',exact:true}).click()
  await page.getByRole('button',{name:'Capture after',exact:true}).click()
  await expect(added.getByRole('button',{name:'Run suite after',exact:true})).toBeEnabled({timeout:45000})
  await expect(added.getByText('Added during this change. No before recording is available for this suite.',{exact:true})).toBeVisible()
  await page.getByRole('tab',{name:'Videos',exact:true}).click()
  await expect(added.getByLabel('After interaction video',{exact:true})).toHaveCount(0)
  await expect(added.getByText('No tests selected for video comparison.',{exact:true})).toBeVisible()
  const payload=await page.locator('#hub-data').textContent().then(JSON.parse)
  const disabled=payload.props.session.suites.find(suite=>suite.name==='New component').runs.at(-1)
  expect(disabled.report.tests).toHaveLength(2)
  expect(disabled.report.tests.every(test=>test.outcome==='expected')).toBe(true)
  const enabled=payload.props.session.suites.find(suite=>suite.name==='Feature suite').runs.at(-1)
  expect(enabled.report.tests).toHaveLength(6)
  expect(enabled.report.tests.filter(test=>test.outcome!=='skipped').every(test=>test.attachments.some(attachment=>attachment.contentType==='video/webm'))).toBe(true)
  expect(readdirSync(repo).some(file=>file.startsWith('.change-hub-'))).toBe(false)
  await page.reload()
  await expect(page.getByRole('checkbox',{name:'Videos for file feature.spec.mjs',exact:true})).not.toBeChecked()
  await page.getByRole('combobox',{name:'Test suite',exact:true}).selectOption({label:'Feature suite'})
  await expect(suite.locator('.video-pair')).toHaveCount(2)
  const mobile=page.getByRole('checkbox',{name:'Video for feature.spec.mjs › opens component (mobile)',exact:true})
  await mobile.uncheck()
  await expect.poll(()=>page.getByRole('checkbox',{name:'Videos for file feature.spec.mjs',exact:true}).evaluate(input=>input.indeterminate)).toBe(true)
  await page.getByRole('button',{name:'Apply video selection',exact:true}).click()
  await expect(suite.locator('.video-pair')).toHaveCount(1)
  await expect(evidence.getByText('Selected video pairs: 1',{exact:true})).toBeVisible()
  await expect(evidence.locator('.test-metrics > div').filter({hasText:'Executed'}).locator('dd')).toHaveText('4')
  await page.reload()
  await expect(mobile).not.toBeChecked()
  await expect(resumeFile).not.toBeChecked()
  await expect(suite.locator('.video-pair')).toHaveCount(1)
  await page.screenshot({path:'test-results/videos-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/videos-mobile.png',fullPage:true})
  expect(errors).toEqual([])
 }finally{rmSync(repo,{recursive:true,force:true})}
})
