import { recordedAction } from './support/recorded-actions.js';
import {test,expect} from '@playwright/test'
import {mkdtempSync,writeFileSync,symlinkSync,rmSync,mkdirSync,readdirSync} from 'node:fs'
import {join,resolve} from 'node:path'
import {execFileSync} from 'node:child_process'

test('video-first captures, developer diffs and suites added during a change',async({page}, testInfo)=>{
 testInfo.annotations.push({type:'compact-recording',description:'Short action pauses keep the complete workflow within the capture timeout.'});
 test.setTimeout(150000)
 const repo=mkdtempSync(resolve('storage/framework/testing/suite-'))
 const git=args=>execFileSync('git',args,{cwd:repo})
 const errors=[];page.on('pageerror',error=>errors.push(error.message))
 try {
  git(['init','-q']);symlinkSync(resolve('node_modules'),join(repo,'node_modules'),'dir');writeFileSync(join(repo,'.gitignore'),'node_modules\n')
  mkdirSync(join(repo,'src'))
  writeFileSync(join(repo,'src/App.tsx'),'export function Home() { return <a href="/old">Home</a> }')
  writeFileSync(join(repo,'state.txt'),'Before feature')
  writeFileSync(join(repo,'playwright.config.mjs'),`export default {testDir:'.',testMatch:'*.spec.mjs',timeout:10000,use:{video:'on'},projects:[{name:'desktop'},{name:'mobile',use:{viewport:{width:390,height:844}}}]}`)
  writeFileSync(join(repo,'resume.spec.mjs'),`import {test,expect} from '@playwright/test';test('opens resume',async({page})=>{await page.setContent('<h1>Resume</h1>');await expect(page.locator('h1')).toHaveText('Resume')})`)
  writeFileSync(join(repo,'feature.spec.mjs'),`import {test,expect} from '@playwright/test';import {readFileSync} from 'node:fs';test('opens component',async({page},info)=>{info.annotations.push({type:'covers',description:'src/App.tsx'});const title=readFileSync(new URL('./state.txt',import.meta.url),'utf8');await page.route('http://fixture.test/**',route=>route.fulfill({contentType:'text/html',body:'<main><h1>'+title+'</h1><button>Save</button></main>'}));await page.goto('http://fixture.test/');await page.evaluate(value=>console.log(value),title);await page.getByRole('button').click();await expect(page.locator('h1')).toHaveText(title);await info.attach('checkpoint',{body:await page.screenshot(),contentType:'image/png'});await page.waitForTimeout(700)});`)
  git(['add','.']);git(['-c','user.name=Test','-c','user.email=test@example.invalid','commit','-qm','fixture'])
  await page.goto('/projects/create')
  await recordedAction(page, page.getByLabel('Project name',{exact:true}), 'fill', 'Suite fixture')
  await recordedAction(page, page.getByLabel('Repository directory',{exact:true}), 'fill', repo)
  await recordedAction(page, page.getByLabel('Playwright config path',{exact:true}), 'fill', 'playwright.config.mjs')
  await recordedAction(page, page.getByLabel('Default suite name',{exact:true}), 'fill', 'Feature suite')
  await recordedAction(page, page.getByRole('button',{name:'Connect project',exact:true}), 'click')
  await recordedAction(page, page.getByRole('button',{name:'Save environment',exact:true}), 'click')
  await recordedAction(page, page.getByLabel('Session title',{exact:true}), 'fill', 'Feature comparison')
  await recordedAction(page, page.getByRole('button',{name:'Create session',exact:true}), 'click')
  const manager=page.getByRole('region',{name:'Playwright suites',exact:true})
  const submit=async button=>{await Promise.all([page.waitForResponse(response=>response.request().method()==='POST'),recordedAction(page, button, 'click')]);await expect(page.locator('form[aria-busy="true"]')).toHaveCount(0)}
  const openSuite=async name=>{for(const open of await manager.locator(':scope > .suite-table-scroll > .suite-table > tbody > tr > th > button[aria-expanded="true"]').all()){if((await open.textContent()).trim()!=='▾ '+name)await recordedAction(page,open,'click')}const toggle=manager.getByRole('button',{name:'▸ '+name,exact:true});if(await toggle.isVisible())await recordedAction(page, toggle, 'click')}
  const suite=page.getByRole('region',{name:'Suite Feature suite',exact:true})
  await expect(suite).toBeVisible()
  await expect(page.getByRole('tab',{name:'Videos',exact:true})).toBeVisible()
  await expect(page.getByText('What changed in this view',{exact:true})).toHaveCount(0)
  await expect(manager.getByRole('button',{name:'▸ Feature suite',exact:true})).toHaveAttribute('aria-expanded','false')
  await openSuite('Feature suite')
  await submit(manager.getByRole('button',{name:'Refresh test list',exact:true}))
  await openSuite('Feature suite')
  const resumeFile=page.getByRole('checkbox',{name:'Videos for file resume.spec.mjs',exact:true})
  await expect(resumeFile).toBeChecked()
  await recordedAction(page, resumeFile, 'uncheck')
  await submit(page.getByRole('button',{name:'Apply video selection',exact:true}))
  await openSuite('Feature suite')
  await expect(resumeFile).not.toBeChecked()
  await recordedAction(page, page.getByRole('button',{name:'Capture before',exact:true}), 'click')
  await expect(suite.getByRole('button',{name:'Session baseline reused',exact:true})).toBeVisible({timeout:45000})
  await expect(suite.locator('.video-pair')).toHaveCount(1)
  const evidence=page.getByRole('region',{name:'Test coverage summary',exact:true})
  await expect(evidence.locator('.test-metrics > div').filter({hasText:'Executed'}).locator('dd')).toHaveText('4')
  await expect(evidence.getByText('New tests: Not compared',{exact:true})).toBeVisible()
  const pair=suite.locator('.video-pair').first()
  const beforeVideo=pair.getByLabel('Before interaction video',{exact:true})
  const beforeURL=await beforeVideo.getAttribute('src')
  await recordedAction(page, page.getByRole('tab',{name:'Videos',exact:true}), 'click')
  const recordings=page.getByRole('group',{name:'Recordings',exact:true})
  await expect(recordings.getByRole('button')).toHaveCount(2)
  await recordedAction(page, recordings.getByRole('button').last(), 'click')
  await expect(pair).toHaveAttribute('aria-label', /^mobile:/)
  await recordedAction(page, page.getByLabel('Find a recording'), 'fill', 'not-a-recording')
  await expect(page.getByText('No recordings match this search.',{exact:true})).toBeVisible()
  await recordedAction(page, page.getByLabel('Find a recording'), 'fill', '')
  await recordedAction(page, recordings.getByRole('button').first(), 'click')
  await expect(pair.getByRole('button',{name:'Play in fullscreen',exact:true})).toBeEnabled()
  await recordedAction(page, pair.getByRole('button',{name:'Play before',exact:true}), 'click')
  await expect.poll(()=>beforeVideo.evaluate(video=>video.currentTime)).toBeGreaterThan(0)
  writeFileSync(join(repo,'state.txt'),'After feature')
  writeFileSync(join(repo,'src/App.tsx'),'export function Home() { return <a href="/new">Home</a> }; fetch("/api/user")')
  writeFileSync(join(repo,'src/New.ts'),'export type NewSettings = { enabled: boolean }')
  writeFileSync(join(repo,'new.spec.mjs'),`import {test} from '@playwright/test';test.skip('new unfinished behavior',async()=>{});`)
  await recordedAction(page, page.getByRole('tab',{name:'Overview',exact:true}), 'click')
  await recordedAction(page, page.getByRole('button',{name:'Capture after',exact:true}), 'click')
  await expect(page.getByRole('button',{name:'Capture after',exact:true})).toBeEnabled({timeout:45000})
  await expect(beforeVideo).toHaveAttribute('src',beforeURL)
  await expect(evidence.locator('.test-metrics > div').filter({hasText:'Executed'}).locator('dd')).toHaveText('4')
  await expect(evidence.locator('.test-metrics > div').filter({hasText:'Skipped'}).locator('dd')).toHaveText('2')
  await expect(evidence.getByText('New tests: 2',{exact:true})).toBeVisible()
  await expect(evidence.getByText('Selected video pairs: 2',{exact:true})).toBeVisible()
  await recordedAction(page, evidence.getByText('Changed areas: 1 without identified coverage / 2 changed files',{exact:true}), 'click')
  await expect(evidence.locator('.coverage-area').filter({hasText:'src/New.ts'})).toContainText('Coverage not identified')
  await expect(evidence.locator('.coverage-area').filter({hasText:'src/App.tsx'})).toContainText('2 declared test links')
  await recordedAction(page, page.getByRole('tab',{name:'Videos',exact:true}), 'click')
  await recordedAction(page, pair.getByRole('button',{name:'Play both',exact:true}), 'click')
  await expect.poll(()=>pair.getByLabel('After interaction video',{exact:true}).evaluate(video=>video.currentTime)).toBeGreaterThan(0)
  await recordedAction(page, pair.getByRole('button',{name:'Pause',exact:true}), 'click')
  const inlineWidth=await beforeVideo.evaluate(video=>video.getBoundingClientRect().width)
  await recordedAction(page, pair.getByRole('button',{name:'Play in fullscreen',exact:true}), 'click')
  await expect.poll(()=>page.evaluate(()=>document.fullscreenElement?.classList.contains('fullscreen-comparison'))).toBe(true)
  await expect(pair.getByRole('button',{name:'Exit fullscreen',exact:true})).toBeFocused()
  await expect.poll(()=>beforeVideo.evaluate(video=>video.currentTime)).toBeGreaterThan(0)
  await expect.poll(()=>pair.getByLabel('After interaction video',{exact:true}).evaluate(video=>video.currentTime)).toBeGreaterThan(0)
  expect(await beforeVideo.evaluate(video=>video.getBoundingClientRect().width)).toBeGreaterThan(inlineWidth)
  await recordedAction(page, pair.getByRole('button',{name:'Pause',exact:true}), 'click')
  await expect.poll(()=>beforeVideo.evaluate(video=>video.paused)).toBe(true)
  await expect.poll(()=>pair.getByLabel('After interaction video',{exact:true}).evaluate(video=>video.paused)).toBe(true)
  await recordedAction(page, pair.getByLabel('Interaction playback speed'), 'selectOption', '0.5')
  expect(await beforeVideo.evaluate(video=>video.playbackRate)).toBe(0.5)
  expect(await pair.getByLabel('After interaction video',{exact:true}).evaluate(video=>video.playbackRate)).toBe(0.5)
  await page.screenshot({path:'test-results/fullscreen-comparison.png'})
  await recordedAction(page, pair.getByRole('button',{name:'Exit fullscreen',exact:true}), 'click')
  await expect.poll(()=>page.evaluate(()=>document.fullscreenElement === null)).toBe(true)
  await expect(pair.getByRole('button',{name:'Play in fullscreen',exact:true})).toBeFocused()
  await recordedAction(page, pair.getByRole('button',{name:'Play in fullscreen',exact:true}), 'click')
  await expect.poll(()=>page.evaluate(()=>document.fullscreenElement !== null)).toBe(true)
  await page.keyboard.press('Escape')
  await expect.poll(()=>page.evaluate(()=>document.fullscreenElement === null)).toBe(true)
  await recordedAction(page, pair.getByLabel('Interaction playback speed'), 'selectOption', '1')

  await expect(page.getByRole('tab',{name:'Screenshots',exact:true})).toHaveCount(0)
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.setViewportSize({width:1440,height:1000})
  await recordedAction(page, page.getByRole('tab',{name:'Dev details',exact:true}), 'click')
  await recordedAction(page, page.getByRole('button',{name:'Change review',exact:true}), 'click')
  const review=page.getByRole('region',{name:'Change review',exact:true})
  await expect(review).toBeVisible()
  await expect(review.locator('.review-area')).toHaveCount(2)
  await recordedAction(page, review.getByRole('button',{name:'Evidence gaps only',exact:true}), 'click')
  await expect(review.locator('.review-area')).toHaveCount(1)
  await expect(review.locator('.review-area')).toContainText('src/New.ts')
  await recordedAction(page, review.getByRole('button',{name:'Evidence gaps only',exact:true}), 'click')
  await recordedAction(page, review.getByLabel('Find a changed area'), 'fill', 'App.tsx')
  await recordedAction(page, review.locator('.review-area > summary'), 'click')
  await expect(review.locator('.test-result-row')).toHaveCount(2)
  await expect(review.locator('.test-result-row details')).toHaveCount(0)
  await expect(review.getByRole('link',{name:'Video',exact:true}).first()).toBeVisible()
  await expect(review.locator('canvas')).toHaveCount(0)
  await page.screenshot({path:'test-results/change-review-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/change-review-mobile.png',fullPage:true})
  await page.setViewportSize({width:1440,height:1000})
  await recordedAction(page, page.getByRole('button',{name:'Test explorer',exact:true}), 'click')
  const explorer=page.getByRole('region',{name:'Test explorer',exact:true})
  await recordedAction(page, explorer.getByRole('button').filter({hasText:'opens component'}).first(), 'click')
  await recordedAction(page, explorer.getByRole('button',{name:'Console',exact:true}), 'click')
  await expect(explorer.getByLabel('Selected test output')).toContainText('log: After feature')
  await recordedAction(page, explorer.getByRole('button',{name:'Network',exact:true}), 'click')
  await expect(explorer.getByLabel('Selected test output')).not.toContainText('diagnostics were not recorded')
  await recordedAction(page, page.getByRole('button',{name:'Contract diffs',exact:true}), 'click')
  const ui=page.getByRole('region',{name:'UI components and navigation',exact:true})
  await recordedAction(page, ui.locator('.file-diff > summary'), 'click')
  await recordedAction(page, ui.locator('summary').filter({hasText:'Navigation a'}), 'click')
  await expect(ui.locator('.diff-line.removed:visible').filter({hasText:'/old'})).toBeVisible()
  await expect(ui.locator('.diff-line.added:visible').filter({hasText:'/new'})).toBeVisible()
  await page.screenshot({path:'test-results/dev-details-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/dev-details-mobile.png',fullPage:true})
  await page.setViewportSize({width:1440,height:1000})
  await recordedAction(page, page.getByRole('tab',{name:'Overview',exact:true}), 'click')
  await recordedAction(page, page.getByText('Add a Playwright suite',{exact:true}), 'click')
  await recordedAction(page, page.locator('.add-suite').getByLabel('Suite name',{exact:true}), 'fill', 'New component')
  await recordedAction(page, page.locator('.add-suite').getByLabel('Test title filter (optional regex)',{exact:true}), 'fill', 'opens component')
  await submit(page.getByRole('button',{name:'Add suite',exact:true}))
  await recordedAction(page, page.getByRole('combobox',{name:'Test suite',exact:true}), 'selectOption', {label:'New component'})
  const added=page.getByRole('region',{name:'Suite New component',exact:true})
  await openSuite('New component')
  await submit(manager.getByRole('button',{name:'Refresh test list',exact:true}))
  await openSuite('New component')
  await recordedAction(page, page.getByRole('checkbox',{name:'Videos for file feature.spec.mjs',exact:true}), 'uncheck')
  await submit(page.getByRole('button',{name:'Apply video selection',exact:true}))
  await recordedAction(page, page.getByRole('tab',{name:'Overview',exact:true}), 'click')
  await recordedAction(page, page.getByRole('button',{name:'Capture after',exact:true}), 'click')
  await expect(added.getByRole('button',{name:'Run suite after',exact:true})).toBeEnabled({timeout:45000})
  await expect(added.locator('.baseline-notice')).toContainText('Session baseline locked')
  await recordedAction(page, page.getByRole('tab',{name:'Videos',exact:true}), 'click')
  await expect(added.getByLabel('After interaction video',{exact:true})).toHaveCount(0)
  await expect(added.getByText('No tests selected for video comparison.',{exact:true})).toBeVisible()
  const currentHtml=await (await page.request.get(page.url())).text()
  const payload=JSON.parse(currentHtml.match(/<script id="hub-data" type="application\/json">(.*?)<\/script>/s)[1])
  const disabled=payload.props.session.suites.find(suite=>suite.name==='New component').runs.at(-1)
  expect(disabled.report.tests).toHaveLength(2)
  expect(disabled.report.tests.every(test=>test.outcome==='expected')).toBe(true)
  const enabled=payload.props.session.suites.find(suite=>suite.name==='Feature suite').runs.at(-1)
  expect(enabled.report.tests).toHaveLength(6)
  expect(enabled.report.tests.filter(test=>test.outcome!=='skipped').every(test=>test.attachments.some(attachment=>attachment.contentType==='video/webm'))).toBe(true)
  expect(readdirSync(repo).some(file=>file.startsWith('.change-hub-'))).toBe(false)
  await recordedAction(page, page.getByRole('tab',{name:'Overview',exact:true}), 'click')
  await page.reload()
  await openSuite('New component')
  await expect(page.getByRole('checkbox',{name:'Videos for file feature.spec.mjs',exact:true})).not.toBeChecked()
  await recordedAction(page, manager.getByRole('button',{name:'▾ New component',exact:true}), 'click')
  await recordedAction(page, page.getByRole('combobox',{name:'Test suite',exact:true}), 'selectOption', {label:'Feature suite'})
  await expect(suite.locator('.video-pair')).toHaveCount(1)
  await openSuite('Feature suite')
  await expect(manager.getByRole('button',{name:'▸ feature.spec.mjs',exact:true})).toHaveAttribute('aria-expanded','false')
  await recordedAction(page, manager.getByRole('button',{name:'▸ feature.spec.mjs',exact:true}), 'click')
  const mobile=page.getByRole('checkbox',{name:'Video for feature.spec.mjs › opens component (mobile)',exact:true})
  await recordedAction(page, mobile, 'uncheck')
  await expect.poll(()=>page.getByRole('checkbox',{name:'Videos for file feature.spec.mjs',exact:true}).evaluate(input=>input.indeterminate)).toBe(true)
  await submit(page.getByRole('button',{name:'Apply video selection',exact:true}))
  await expect(suite.locator('.video-pair')).toHaveCount(1)
  await expect(evidence.getByText('Selected video pairs: 1',{exact:true})).toBeVisible()
  await expect(evidence.locator('.test-metrics > div').filter({hasText:'Executed'}).locator('dd')).toHaveText('4')
  await page.reload()
  await openSuite('Feature suite')
  await recordedAction(page, manager.getByRole('button',{name:'▸ feature.spec.mjs',exact:true}), 'click')
  await expect(mobile).not.toBeChecked()
  await expect(resumeFile).not.toBeChecked()
  await expect(suite.locator('.video-pair')).toHaveCount(1)
  await recordedAction(page, page.getByRole('tab',{name:'Videos',exact:true}), 'click')
  await page.screenshot({path:'test-results/videos-desktop.png',fullPage:true})
  await page.setViewportSize({width:390,height:844})
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true)
  await page.screenshot({path:'test-results/videos-mobile.png',fullPage:true})
  await page.setViewportSize({width:1440,height:1000})
  await recordedAction(page, page.getByRole('tab',{name:'Overview',exact:true}), 'click')
  await recordedAction(page, manager.getByRole('button',{name:'▾ Feature suite',exact:true}), 'click')
  await openSuite('New component')
  await recordedAction(page, manager.getByText('Edit suite',{exact:true}), 'click')
  await recordedAction(page, manager.locator('.suite-settings').getByLabel('Suite name',{exact:true}), 'fill', 'Renamed component')
  await submit(manager.getByRole('button',{name:'Save suite',exact:true}))
  await expect(manager.getByRole('button',{name:'▾ Renamed component',exact:true})).toBeVisible()
  await openSuite('Renamed component')
  await recordedAction(page, manager.getByRole('button',{name:'Remove suite',exact:true}), 'click')
  await recordedAction(page, manager.getByRole('button',{name:'Cancel',exact:true}), 'click')
  await expect(manager.getByRole('button',{name:'Confirm removal',exact:true})).toHaveCount(0)
  await recordedAction(page, manager.getByRole('button',{name:'Remove suite',exact:true}), 'click')
  await submit(manager.getByRole('button',{name:'Confirm removal',exact:true}))
  await expect(manager.getByRole('button',{name:'▸ Renamed component',exact:true})).toHaveCount(0)
  await expect(manager.getByRole('button',{name:'▸ Feature suite',exact:true})).toBeVisible()
  await page.screenshot({path:'test-results/suite-overview-desktop.png',fullPage:true})
  expect(errors).toEqual([])
 }finally{rmSync(repo,{recursive:true,force:true})}
})
